### ISSUE TITLE
Random wad sometimes doesn't appear to work

### ISSUE THREAD

**Issue by karlpet** [karlpet/WadLauncher#37]
Sometimes it doesn't seem like the random url functions correctly.

Need investigation.

error trace:
```
Traceback (most recent call last):
  File "/home/karlpet/Git/WadLauncher/src/main/python/main.py", line 25, in <module>
    exit_code = appctxt.app.exec_()
  File "/home/karlpet/Git/WadLauncher/src/main/python/app/controllers/IdgamesDetailController.py", line 38, in set_data
    self.view.setData(result)
  File "/home/karlpet/Git/WadLauncher/src/main/python/app/views/IdgamesDetailView.py", line 28, in setData
    label.setText(str(item.get(key)) or 'unknown')

```

**Comment by karlpet** [comment]
Solved by de-coupling the Search->Detail code (via using wads broadcasting instead of imperative coding.)
